### PR TITLE
Allow for params to be passed from Route to Components

### PR DESCRIPTION
**Pull request by evanderkoogh**
This makes it possible to set properties on a Route object that will be
passed to the component(s) inside that route.

For example:

<Route
        path="/"
        component={WidgetContainer}
        props={{ hello: 'World' }}
        queries={{
          widget: () => Relay.QL`query { widget }`,
        }}
      >

### CODE REVIEW

**Comment by taion** [comment]
This isn't required. Just use `this.props.route.whatever`.

**Comment by evanderkoogh** [comment]
Well.. that makes me feel welcome to contribute more code in the future.. 

This would mean wrapping non-Relay aware components into a Relay-Aware component into a RelayContainer right? I might have some time to add this to the documentation at the very least for the next person to come along..

**Comment by taion** [comment]
No, this isn't react-router-relay specific. It's purely a React Router thing.

Any React Router route component can access the route object as `this.props.route`, and every prop on the `<Route>` (or plain route object if not using JSX routes) can be accessed as a property on `this.props.route`.

**Comment by evanderkoogh** [comment]
Sorry, meant to say non-*Route* aware components into a *Route*-Aware one, into a RelayContainer.

**Comment by taion** [comment]
You can always spread out that prop from the route component and pass it down as needed, or handle it yourself in a fully custom `createElement` if it's really necessary.

Your route-aware components don't have to be relay containers. This is all pure React Router stuff, no data integration relevant.

How you do that that's all up to you, but "passing props statically from route to route component" hasn't got anything to do with Relay integration.

**Pull request closed without merging**
