### PR TITLE
Allow passing a function as environment prop in renderRouterContext()

### PR DESCRIPTION
**Pull request by hisapy**
Hi guys and girls,

This is useful to set a new Relay.Environment() for example in login and logout. For example:

```javascript
ReactDOM.render(
  <Router history={browserHistory}
    render={applyRouterMiddleware(useRelay)}
    environment={() => Auth.getEnvironment()}> {/* <------ Hey you!!!*/}
    <Route path="/" component={Hello}/>
    <Route path="/login" component={Login}/>
    <Route path="/admin" component={AdminLayout} onEnter={requireAuth}>
      <IndexRoute component={Hello}/>
      <Route path="star-wars" component={StarWarsApp} queries={StarWarsQueries}/>
      <Route path="graphiql" component={GraphiQL} />
    </Route>
  </Router>,
  document.getElementById('react-root')
);
```

The code for Auth is [here](https://github.com/iporaitech/pwr2-docker/blob/develop/web/static/js/lib/auth.js). You can also see the whole app in there.

Have a nice Friday!

Hisa

### CODE REVIEW

**Comment by taion** [comment]
Why not just handle this by wrapping `<Router>` in another component (or using another middleware) that passes down `environment` as a prop? I use this pattern and it's worked fine for me so far.

**Comment by hisapy** [comment]
Well, if I wrap the Router in another component it won't look as sexy as it looks now. Can you please provide an example of how to wrap it? I tried that before forking this but I wasn't able to achieve the same behaviour. 

On the other hand, What do you mean by another middleware? Do you mean not using react-router-relay? 

_PS: taking into account use cases like [this](https://github.com/facebook/relay/issues/1025#issuecomment-207162568) which I believe are more common than edge, I think it would be better to always pass a function returning an environment and get rid of the **if** to check if environment is an object or a function. Of course, that would not be backwards compatible_

**Comment by taion** [comment]
You follow exactly the logic that @josephsavona has in that comment, but you use `setState`, and pass down `this.state.environment` into `<Router>`. It doesn't actually work to just use a function there because you need to trigger re-rendering/re-fetching anyway, so you need imperative wrapping code to make that all happen.

**Comment by hisapy** [comment]
@taion can you please provide an example of the pattern you're using then? 

Thanks in advance. I'd really appreciate your guidance here.

**Comment by taion** [comment]
You just have a component that renders

```js
<Router environment={this.state.environment} //...
```

Or clone and pass down the prop in a router middleware that goes before the Relay middleware. That's all it is – just pass down the prop.

**Comment by hisapy** [comment]
Ok thanks @taion ... I'll give it a try.

**Comment by edipox** [comment]
Hi @taion  I am also having this issue. I belive I did what you mentioned. I've created a wrapper and I am using `setState` to make react re render the router when the environment changes. 

Here is the code: https://github.com/iporaitech/pwr2-docker/blob/issue-46-relay-env/apps/webapp/web/static/js/index.js#L37

But the problem is that when react re renders the router I get this error:
```
browser.js:49 Warning: [react-router] You cannot change <Router routes>; it will be ignored
```

Have I missed something? Do you have any suggestion about what can I do to fix this?

**Comment by taion** [comment]
Extract your routes into a singleton so they don't break referential equality. (e.g. a top level `const routes = ...`).

**Comment by edipox** [comment]
It works! Thank you very much @taion
I will add another comment with an example of the solution so anyone that also want something like this can find this solution easily

**Comment by edipox** [comment]
Well for anyone that would want to use environment as a function, here is an alternative: 

```javascript

/* 
  Extract routes as a constant so it is re used in every render 
  To avoid errors like: 
  Warning: [react-router] You cannot change <Router routes>; it will be ignored 
 */
const routes = (
  <Route path="/">
    ...
  </Route>
)


/*
  Wrap the routes in another component so you can use the state to trigger
  react render every time the environment changes
*/
class Application extends React.Component{

  constructor(props){
    super(props);
    this.state = { environment: getEnvironment() };
  }
  
  /* 
    Now every time you change the state's environment
    For example with 'handleLogout', react will re render the routes
  */
  handleLogout(){
    this.setState({ environment: getEnvironment() })
  }

  render(){
    return (
      <Router ...
        environment={this.state.environment}>
        {routes}
      </Router>
    );
  }
}

```

**Comment by panayi** [comment]
With an identical approach as above, when `<Router>` is re-rendered (and a new environment is passed), I get the following warning:

```
Warning: RelayContainer: Expected prop `viewer` to be supplied to `Connect(Header)`, but got `undefined`. Pass an explicit `null` if this is intentional.
```

I tried to conditionally render the routes tree as below, but strangely `viewer` **is** defined. `Connect(Header)` is a child of `App`:

```
export const createRoutes = () => ({
  path: '/',
  component: App,
  name: 'Home',
  queries: { viewer },
  indexRoute: Home,
  render: ({ props, routerProps, element }) => {
    console.log(props)
    if (!props || !props.viewer) {
      return <div {...routerProps}>Loading</div>
    }
    return React.cloneElement(element, props)
  }
})
```

**Comment by hisapy** [comment]
If I'm not wrong, in the render callback you're passing to `createRoutes()` you're rendering the App element. That said, you should pass viewer to your `Connect(Header)` in the `render()` function of your `App` component. 

Something like the following should do the job:

```javascript
// render function of App
render() {
  const { children, viewer, ...otherProps } = this.props;
  return (
    <div>
      {/* other markup and components here */}
      { React.cloneElement(children, {viewer}, ...otherProps) }
    </div>
  )
}


```

**Pull request closed without merging**
