### PR TITLE
Fix forwarding props into route components

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
Replaces https://github.com/relay-tools/react-router-relay/pull/104.

**Comment by denvned** [comment]
I think we still need to pass the component key to `createElement` to be compatible with the *react-router* behaviour. And passing it to `renderFetched`, `renderLoading`, and `renderFailure` is probably even more important, because otherwise these methods cannot have any conditional logic dependent on which of the named components has been fetched, loaded, or failed.

**Comment by taion** [comment]
Well... it was already broken anyway, since key doesn't make its way into `props`. Hmm.

Unfortunately the current `renderLoading` and `renderFailure` APIs don't even give me a space to inject the key... only `renderFetched` has any capacity to receive the relevant data.

**Comment by denvned** [comment]
> Well... it was already broken anyway, since key doesn't make its way into `props`.

What do you mean? I passed the `key` inside the `routerProps` prop, so it survived. Otherwise named components would not work at all.

> Unfortunately the current `renderLoading` and `renderFailure` APIs don't even give me a space to inject the key...

Yeah. But, is it that important to keep these callbacks fully compatible with `Relay.RootContainer` callbacks? `Relay.RootContainer` is going to be deprecated soon anyway.

**Comment by taion** [comment]
A component can't observe its own key though. Support here was actually the only reason I added `key` to `RouterContext` upstream in the first place. I will patch back in the key, though, just so we unbreak that.

**Comment by taion** [comment]
@denvned 

I'm fixing the `key` handling in https://github.com/relay-tools/react-router-relay/pull/106 (though I'd be surprised if this caused any issues in practice). Note that in #105, I renamed the prop to `componentKey` to get the key in; this just fixes passing the key to the upstream `createElement` function.

I'm not terribly eager to change the signatures of the lifecycle hooks for rendering. Especially given the impending deprecation of `RootContainer`, I don't really want to spend time figuring out and documenting a new API.

**Pull request merged**
