### PR TITLE
Use RelayRenderer-style API

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
This replaces https://github.com/relay-tools/react-router-relay/pull/123.

Routes now take a `render` callback. The semantics try to mimic `RelayRenderer`, except that it's possible to have `props` be non-`null` while `ready` is `false`, in the event that new data is being fetched, but none of the params for the route in question have changed.

**Comment by taion** [comment]
This does not address https://github.com/relay-tools/react-router-relay/issues/68. I haven't had time to look at that yet.

**Comment by taion** [comment]
I'm going to merge this for now, then make a few other changes, then cut this as an RC.

**Comment by taion** [comment]
This (and other changes) are out as v0.13.0-rc.1.

**Comment by akre54** [comment]
How do I actually migrate for this update? What concrete changes do I need to make in my app?

**Comment by taion** [comment]
See https://github.com/relay-tools/react-router-relay/releases/tag/v0.13.0.

**Comment by akre54** [comment]
Nevermind, I figured it out (I have to pass `Relay.Store` as the `environment` prop to Router).

I read the changelog which is how I found this issue.

In the future it would help to have some upgrade guidance on breaking changes like this. I hadn't come across `Relay.Environment` in my code before so I looked up the docs and tried to create a new Environment but got a slew of other errors. Finally I saw that `Relay.Store` is the default exported global singleton (which I am familiar with) and tried that. It'd be nice not to have to guess and check for these types of upgrades.

**Comment by taion** [comment]
The updated README demonstrates the new usage, and the tests show the code in use, plus all the changes are documented in the release notes.

**Comment by akre54** [comment]
The readme actually doesn't have any mention of `environment`. And I looked in the tests (as part of the changes to this pull request) but see nothing about Relay.store. I saw a bit about creating the environment, which I tried, but then it complained about a lack of network layer (your tests use a local schema adapter). After a couple more tries I found the solution by looking at the Relay docs.

I'm greatful for all your work, but please have some empathy for your devs. For any breaking change like this it would help to have a bit more guidance from your end to ease the pain on ours. Especially since I'm not intimately familiar with the internals of Relay.

**Comment by taion** [comment]
The README says explicitly:

> pass in a Relay environment to `<Router>`

Each example in the README also uses `environment={Relay.Store}` as the pattern most suitable to use cases that don't explicitly require contextual Relay environments.

**Pull request merged**
