### PR TITLE
Remove `getQuery` and `getQueryNames` from RouteAggregator.

### PR DESCRIPTION
**Pull request by cpojer**
Relay 0.2 just came out :)

### CODE REVIEW

**Comment by taion** [comment]
Should this also bump the `react-relay` dependency version?

**Comment by devknoll** [comment]
We don't actually have any dependencies listed? Or am I blind?

**Comment by taion** [comment]
Oops. I'll fix that separately.

**Comment by cpojer** [comment]
Yeah it is nowhere to be found.

**Comment by devknoll** [comment]
:+1:

**Pull request merged**
